appuser_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0DkRVZi1A2m0SO1mvEumg28iFUUqM0R1KmFIyC5HU86WcE9L5LYyKKAdxI9ofZHeZ+kh9kD3MDa+nRfOhG8hBVawlmSj4DGv6Bfc12efteLLdoKG/7/c20+WIY0nW3O0mdHONfJyLjcFb4BeHpcnEraiINlVaUObdvWoYBj7VfRNnxZAL9sdJNGxyjIGxS1shSTbu2YQeeMHQ4ZNLll5cfGxOnIbM1B12uNqdpUiBDkQQ2E/aL6IqgCtN9ToU5Q9Qs29ln/AKXCVpbLns2DVOAeVqJQPxe/pgb/lsv50DBFCHl/zJCZIzrUUmU+gagraopERE/G9BIgTkS7WO/99f"

tripwire_site_pass: "SitePass123!"
tripwire_local_pass: "LocalPass123!"
